export default [
  {
    id: 0,
    //"created_by": 1,
    food_id: 1,
    restaurant_id: 1,
    pick_up: '후문',
    openKakao: 'httpaaa',
    content: '치킨먹을사람',
    dormitory: 'SOOKMYUNG',
    end_time: '2022-12-28 00:00:00',
  },
  {
    id: 1,
    //"created_by": 1,
    food_id: 1,
    restaurant_id: 2,
    pick_up: '후문',
    openKakao: 'httpaaa',
    content: '베라먹을사람',
    dormitory: 'SOOKMYUNG',
    end_time: '2022-12-28 00:00:00',
  },
  {
    id: 2,
    //"created_by": 1,
    food_id: 1,
    restaurant_id: 3,
    pick_up: '후문',
    openKakao: 'httpaaa',
    content: '엽떡먹을사람',
    dormitory: 'SOOKMYUNG',
    end_time: '2022-12-28 00:00:00',
  },
  {
    id: 3,
    //"created_by": 1,
    food_id: 1,
    restaurant_id: 4,
    pick_up: '후문',
    openKakao: 'httpaaa',
    content: '피자헛먹을사람',
    dormitory: 'SOOKMYUNG',
  },
  {
    id: 4,
    //"created_by": 1,
    food_id: 1,
    restaurant_id: 5,
    pick_up: '후문',
    openKakao: 'httpaaa',
    content: '교촌먹을사람',
    dormitory: 'SOOKMYUNG',
    end_time: '2022-12-28 00:00:00',
  },
  {
    id: 5,
    //"created_by": 1,
    food_id: 1,
    restaurant_id: 6,
    pick_up: '후문',
    openKakao: 'httpaaa',
    content: '치킨먹을사람',
    dormitory: 'SOOKMYUNG',
    end_time: '2022-12-28 00:00:00',
  },
  {
    id: 6,
    //"created_by": 1,
    food_id: 1,
    restaurant_id: 7,
    pick_up: '후문',
    openKakao: 'httpaaa',
    content: '삼겹살먹을사람',
    dormitory: 'SOOKMYUNG',
    end_time: '2022-12-28 00:00:00',
  },
  {
    id: 7,
    //"created_by": 1,
    food_id: 1,
    restaurant_id: 8,
    pick_up: '후문',
    openKakao: 'httpaaa',
    content: '족발먹을사람',
    dormitory: 'SOOKMYUNG',
    end_time: '2022-12-28 00:00:00',
  },
  {
    id: 8,
    //"created_by": 1,
    food_id: 1,
    restaurant_id: 9,
    pick_up: '후문',
    openKakao: 'httpaaa',
    content: '치킨먹을사람',
    dormitory: 'SOOKMYUNG',
    end_time: '2022-12-28 00:00:00',
  },
  {
    id: 9,
    //"created_by": 1,
    food_id: 1,
    restaurant_id: 10,
    pick_up: '후문',
    openKakao: 'httpaaa',
    content: '치킨먹을사람',
    dormitory: 'SOOKMYUNG',
    end_time: '2022-12-28 00:00:00',
  },
  {
    id: 10,
    //"created_by": 1,
    food_id: 1,
    restaurant_id: 11,
    pick_up: '후문',
    openKakao: 'httpaaa',
    content: '치킨먹을사람',
    dormitory: 'SOOKMYUNG',
    end_time: '2022-12-28 00:00:00',
  },
];
