export default [
  {
    host_id: 1,
    food_id: 3,
    recruits_cnt: 3,
    pick_up: '후문',
    openKakao: 'httpaaa',
    dormitory: 'KOOKMIN',
    end_time: '2022-12-28T11:32:40',
    content: '같이 먹을 사람 괌3',
  },
  {
    host_id: 1,
    food_id: 4,
    recruits_cnt: 3,
    pick_up: '후문',
    openKakao: 'httpaaa',
    dormitory: 'KOOKMIN',
    end_time: '2022-12-28T11:32:40',
    content: '같이 먹을 사람 괌3',
  },
  {
    host_id: 1,
    food_id: 5,
    recruits_cnt: 2,
    pick_up: '후문',
    openKakao: 'httpaaa',
    dormitory: 'KOOKMIN',
    end_time: '2022-12-28T11:32:40',
    content: '같이 먹을 사람 괌3',
  },
  {
    host_id: 1,
    food_id: 6,
    recruits_cnt: 2,
    pick_up: '후문',
    openKakao: 'httpaaa',
    dormitory: 'KOOKMIN',
    end_time: '2022-12-28T11:32:40',
    content: '같이 먹을 사람 괌3',
  },
  {
    host_id: 1,
    food_id: 7,
    recruits_cnt: 2,
    pick_up: '후문',
    openKakao: 'httpaaa',
    dormitory: 'KOOKMIN',
    end_time: '2022-12-28T11:32:40',
    content: '같이 먹을 사람 괌3',
  },
  {
    host_id: 1,
    food_id: 8,
    recruits_cnt: 2,
    pick_up: '후문',
    openKakao: 'httpaaa',
    dormitory: 'KOOKMIN',
    end_time: '2022-12-28T11:32:40',
    content: '같이 먹을 사람 괌3',
  },
  {
    host_id: 1,
    food_id: 9,
    recruits_cnt: 2,
    pick_up: '후문',
    openKakao: 'httpaaa',
    dormitory: 'KOOKMIN',
    end_time: '2022-12-28T11:32:40',
    content: '같이 먹을 사람 괌3',
  },
  {
    host_id: 1,
    food_id: 10,
    recruits_cnt: 2,
    pick_up: '후문',
    openKakao: 'httpaaa',
    dormitory: 'KOOKMIN',
    end_time: '2022-12-28T11:32:40',
    content: '같이 먹을 사람 괌3',
  },
  {
    host_id: 1,
    food_id: 11,
    recruits_cnt: 2,
    pick_up: '후문',
    openKakao: 'httpaaa',
    dormitory: 'KOOKMIN',
    end_time: '2022-12-28T11:32:40',
    content: '같이 먹을 사람 괌3',
  },
  {
    host_id: 1,
    food_id: 12,
    recruits_cnt: 2,
    pick_up: '후문',
    openKakao: 'httpaaa',
    dormitory: 'KOOKMIN',
    end_time: '2022-12-28T11:32:40',
    content: '같이 먹을 사람 괌3',
  },
  {
    host_id: 1,
    food_id: 13,
    recruits_cnt: 2,
    pick_up: '후문',
    openKakao: 'httpaaa',
    dormitory: 'KOOKMIN',
    end_time: '2022-12-28T11:32:40',
    content: '같이 먹을 사람 괌3',
  },
  {
    host_id: 1,
    food_id: 14,
    recruits_cnt: 3,
    pick_up: '후문',
    openKakao: 'httpaaa',
    dormitory: 'KOOKMIN',
    end_time: '2022-12-28T11:32:40',
    content: '같이 먹을 사람 괌3',
  },
  {
    host_id: 1,
    food_id: 15,
    recruits_cnt: 2,
    pick_up: '후문',
    openKakao: 'httpaaa',
    dormitory: 'KOOKMIN',
    end_time: '2022-12-28T11:32:40',
    content: '같이 먹을 사람 괌3',
  },
];